#!/usr/bin/env sh

# Environment variables :
# * JENKINS_JNLP_URL : JNLP URL
# * JENKINS_AGENT_WORKDIR : agent work directory


if [ -n "$JENKINS_JNLP_URL" ]; then
    JNLP_URL="-jnlpUrl $JENKINS_JNLP_URL"
fi

if [ -n "$JENKINS_AGENT_WORKDIR" ]; then
    AGENT_WORKDIR="-workDir $JENKINS_AGENT_WORKDIR"
fi

JNLP_PROTOCOL_OPTS="-Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=true"
exec java $JAVA_OPTS $JNLP_PROTOCOL_OPTS -jar /usr/share/jenkins/slave.jar $AGENT_WORKDIR $JNLP_URL "$@"
